### ISSUE TITLE
Couldn't find preset "latest" relative to directory ...

### ISSUE THREAD

**Issue by edgarshurtado** [euvl/vue-js-toggle-button#61]
Hi there!

First of all thank you for creating this open-source vue component. Looking at the demo I see is perfect for my project. However, while trying to install it, I came across to the following error message at my webpack build.

```
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-js-toggle-button/src/Button.vue
Module build failed: Error: Couldn't find preset "latest" relative to directory "/home/vagrant/PycharmProjects/zemlabs/node_modules/vue-js-toggle-button"
    at /home/vagrant/PycharmProjects/zemlabs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/vagrant/PycharmProjects/zemlabs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/vagrant/PycharmProjects/zemlabs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/vagrant/PycharmProjects/zemlabs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/vagrant/PycharmProjects/zemlabs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/vagrant/PycharmProjects/zemlabs/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/vagrant/PycharmProjects/zemlabs/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/vagrant/PycharmProjects/zemlabs/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/vagrant/PycharmProjects/zemlabs/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/home/vagrant/PycharmProjects/zemlabs/node_modules/babel-loader/lib/index.js:163:20)
 @ ./~/vue-js-toggle-button/src/Button.vue 7:2-90
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./frontend/app/components/NewProfileForm.vue
 @ ./frontend/app/components/NewProfileForm.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./frontend/app/components/ProfileManagement.vue
 @ ./frontend/app/components/ProfileManagement.vue
```

I have little knowledge about the process webpack and babel do. But searching through internet I found that `babel-preset-latest` is deprecated in favor of using `babel-preset-env` ([found at this thread](https://github.com/chenqingspring/vue-lottie/issues/2)). 

So, I did the wild guess that if I changed the component `.babelrc` to use `balbe-preset-env`, it would work. And it did 😀.  But, I'm not sure if I'm missing something and if you have already a way to deal with this. In case this is something to fix, I could make the PR if you want 😅.

Thank you!

**Comment by edgarshurtado** [comment]
I installed `babel-preset-latest` in my project and also works 🤔. I'm a bit confused since you already had it in your `package.json` as dependency.
